<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    
    public function run(): void
    {
        DB::table('clientes')->insert([
            ['nombre' => 'Juan Pérez', 'direccion' => 'Av. Los Próceres 123, San Isidro', 'telefono' => '987654321', 'email' => 'juan.perez@mail.com', 'dni' => '12345678', 'fecha_nacimiento' => '1985-05-10', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'María García', 'direccion' => 'Calle Las Flores 234, Miraflores', 'telefono' => '987654322', 'email' => 'maria.garcia@mail.com', 'dni' => '23456789', 'fecha_nacimiento' => '1990-09-15', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Luis Torres', 'direccion' => 'Jr. Puno 456, Surco', 'telefono' => '987654323', 'email' => 'luis.torres@mail.com', 'dni' => '34567890', 'fecha_nacimiento' => '1982-02-20', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Ana Rodríguez', 'direccion' => 'Av. Primavera 789, La Molina', 'telefono' => '987654324', 'email' => 'ana.rodriguez@mail.com', 'dni' => '45678901', 'fecha_nacimiento' => '1993-07-12', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Carlos Fernández', 'direccion' => 'Calle Los Álamos 101, San Borja', 'telefono' => '987654325', 'email' => 'carlos.fernandez@mail.com', 'dni' => '56789012', 'fecha_nacimiento' => '1980-11-25', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Sofía Ramírez', 'direccion' => 'Jr. Los Rosales 567, Barranco', 'telefono' => '987654326', 'email' => 'sofia.ramirez@mail.com', 'dni' => '67890123', 'fecha_nacimiento' => '1995-03-08', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'José Martínez', 'direccion' => 'Av. Salaverry 789, Lince', 'telefono' => '987654327', 'email' => 'jose.martinez@mail.com', 'dni' => '78901234', 'fecha_nacimiento' => '1987-12-01', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Laura López', 'direccion' => 'Calle Las Lomas 102, San Miguel', 'telefono' => '987654328', 'email' => 'laura.lopez@mail.com', 'dni' => '89012345', 'fecha_nacimiento' => '1991-04-22', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Diego Castillo', 'direccion' => 'Jr. El Olivar 345, Ate', 'telefono' => '987654329', 'email' => 'diego.castillo@mail.com', 'dni' => '90123456', 'fecha_nacimiento' => '1989-08-18', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Gabriela Ruiz', 'direccion' => 'Av. Javier Prado 678, San Juan de Miraflores', 'telefono' => '987654330', 'email' => 'gabriela.ruiz@mail.com', 'dni' => '01234567', 'fecha_nacimiento' => '1994-10-30', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Andrés Chávez', 'direccion' => 'Calle Los Laureles 201, Surquillo', 'telefono' => '987654331', 'email' => 'andres.chavez@mail.com', 'dni' => '11234567', 'fecha_nacimiento' => '1981-05-16', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Paula Mendoza', 'direccion' => 'Jr. Manco Cápac 222, Jesús María', 'telefono' => '987654332', 'email' => 'paula.mendoza@mail.com', 'dni' => '12234567', 'fecha_nacimiento' => '1992-06-14', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Rodrigo Vega', 'direccion' => 'Av. El Derby 444, Santiago de Surco', 'telefono' => '987654333', 'email' => 'rodrigo.vega@mail.com', 'dni' => '13234567', 'fecha_nacimiento' => '1984-01-25', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Camila Ortiz', 'direccion' => 'Calle El Sol 789, Chorrillos', 'telefono' => '987654334', 'email' => 'camila.ortiz@mail.com', 'dni' => '14234567', 'fecha_nacimiento' => '1996-09-05', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Sebastián Silva', 'direccion' => 'Av. Canadá 123, La Victoria', 'telefono' => '987654335', 'email' => 'sebastian.silva@mail.com', 'dni' => '15234567', 'fecha_nacimiento' => '1986-11-15', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Valeria Rojas', 'direccion' => 'Jr. Manco Cápac 222, Jesús María', 'telefono' => '987654336', 'email' => 'valeria.rojas@mail.com', 'dni' => '16234567', 'fecha_nacimiento' => '1990-12-10', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Jorge Salazar', 'direccion' => 'Calle Las Amapolas 456, Pueblo Libre', 'telefono' => '987654337', 'email' => 'jorge.salazar@mail.com', 'dni' => '17234567', 'fecha_nacimiento' => '1988-03-27', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Daniela Morales', 'direccion' => 'Av. La Marina 789, San Miguel', 'telefono' => '987654338', 'email' => 'daniela.morales@mail.com', 'dni' => '18234567', 'fecha_nacimiento' => '1991-02-17', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Francisco Navarro', 'direccion' => 'Jr. Grau 890, Lima', 'telefono' => '987654339', 'email' => 'francisco.navarro@mail.com', 'dni' => '19234567', 'fecha_nacimiento' => '1983-10-20', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Elena Vásquez', 'direccion' => 'Av. Angamos 345, Miraflores', 'telefono' => '987654340', 'email' => 'elena.vasquez@mail.com', 'dni' => '20234567', 'fecha_nacimiento' => '1997-07-29', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Ricardo García', 'direccion' => 'Jr. Libertad 100, San Juan de Lurigancho', 'telefono' => '987654341', 'email' => 'ricardo.garcia@mail.com', 'dni' => '21234567', 'fecha_nacimiento' => '1990-01-12', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Cynthia Pérez', 'direccion' => 'Calle Lince 321, Lince', 'telefono' => '987654342', 'email' => 'cynthia.perez@mail.com', 'dni' => '22234567', 'fecha_nacimiento' => '1986-05-22', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Pedro Sánchez', 'direccion' => 'Av. Las Américas 456, Callao', 'telefono' => '987654343', 'email' => 'pedro.sanchez@mail.com', 'dni' => '23234567', 'fecha_nacimiento' => '1980-08-19', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Claudia Morales', 'direccion' => 'Calle El Sol 101, San Borja', 'telefono' => '987654344', 'email' => 'claudia.morales@mail.com', 'dni' => '24234567', 'fecha_nacimiento' => '1989-06-01', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Gabriel Ortega', 'direccion' => 'Av. Perú 678, Independencia', 'telefono' => '987654345', 'email' => 'gabriel.ortega@mail.com', 'dni' => '25234567', 'fecha_nacimiento' => '1984-11-30', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Verónica Jiménez', 'direccion' => 'Calle Los Almendros 123, Miraflores', 'telefono' => '987654346', 'email' => 'veronica.jimenez@mail.com', 'dni' => '26234567', 'fecha_nacimiento' => '1993-01-20', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Oscar Castillo', 'direccion' => 'Jr. Cahuide 456, San Juan de Lurigancho', 'telefono' => '987654347', 'email' => 'oscar.castillo@mail.com', 'dni' => '27234567', 'fecha_nacimiento' => '1982-05-16', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Carolina Peña', 'direccion' => 'Av. del Ejército 789, San Isidro', 'telefono' => '987654348', 'email' => 'carolina.pena@mail.com', 'dni' => '28234567', 'fecha_nacimiento' => '1994-03-25', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Ricardo Torres', 'direccion' => 'Calle San José 678, Surquillo', 'telefono' => '987654349', 'email' => 'ricardo.torres@mail.com', 'dni' => '29234567', 'fecha_nacimiento' => '1985-12-12', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Patricia Fernández', 'direccion' => 'Calle Los Cedros 234, Barranco', 'telefono' => '987654350', 'email' => 'patricia.fernandez@mail.com', 'dni' => '30234567', 'fecha_nacimiento' => '1992-07-06', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Luis González', 'direccion' => 'Av. Pardo 890, Miraflores', 'telefono' => '987654351', 'email' => 'luis.gonzalez@mail.com', 'dni' => '31234567', 'fecha_nacimiento' => '1987-02-15', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Javier Hernández', 'direccion' => 'Calle Los Girasoles 123, Villa María del Triunfo', 'telefono' => '987654352', 'email' => 'javier.hernandez@mail.com', 'dni' => '32234567', 'fecha_nacimiento' => '1995-05-10', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Marta Silva', 'direccion' => 'Jr. Piura 654, San Martín de Porres', 'telefono' => '987654353', 'email' => 'marta.silva@mail.com', 'dni' => '33234567', 'fecha_nacimiento' => '1990-09-22', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Raúl Rojas', 'direccion' => 'Av. Grau 123, Callao', 'telefono' => '987654354', 'email' => 'raul.rojas@mail.com', 'dni' => '34234567', 'fecha_nacimiento' => '1988-06-30', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Susana Romero', 'direccion' => 'Jr. Sol 789, La Molina', 'telefono' => '987654355', 'email' => 'susana.romero@mail.com', 'dni' => '35234567', 'fecha_nacimiento' => '1991-10-03', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Adrián López', 'direccion' => 'Av. Los Héroes 432, El Agustino', 'telefono' => '987654356', 'email' => 'adrian.lopez@mail.com', 'dni' => '36234567', 'fecha_nacimiento' => '1992-11-27', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Luz Mendoza', 'direccion' => 'Calle Los Almendros 321, Jesús María', 'telefono' => '987654357', 'email' => 'luz.mendoza@mail.com', 'dni' => '37234567', 'fecha_nacimiento' => '1987-04-14', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Felipe Díaz', 'direccion' => 'Av. Los Ángeles 567, Lince', 'telefono' => '987654358', 'email' => 'felipe.diaz@mail.com', 'dni' => '38234567', 'fecha_nacimiento' => '1990-12-25', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Marcos Pérez', 'direccion' => 'Calle Los Jardines 345, San Miguel', 'telefono' => '987654359', 'email' => 'marcos.perez@mail.com', 'dni' => '39234567', 'fecha_nacimiento' => '1984-03-06', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Esteban Vázquez', 'direccion' => 'Jr. del Sol 890, Miraflores', 'telefono' => '987654360', 'email' => 'esteban.vazquez@mail.com', 'dni' => '40234567', 'fecha_nacimiento' => '1989-01-10', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Ana María Soto', 'direccion' => 'Calle El Rosario 102, San Borja', 'telefono' => '987654361', 'email' => 'ana.soto@mail.com', 'dni' => '41234567', 'fecha_nacimiento' => '1991-08-13', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Carlos Herrera', 'direccion' => 'Jr. Tacna 654, San Juan de Lurigancho', 'telefono' => '987654362', 'email' => 'carlos.herrera@mail.com', 'dni' => '42234567', 'fecha_nacimiento' => '1986-12-21', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Patricia González', 'direccion' => 'Av. San Martín 234, Callao', 'telefono' => '987654363', 'email' => 'patricia.gonzalez@mail.com', 'dni' => '43234567', 'fecha_nacimiento' => '1992-04-17', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Fernando Rodríguez', 'direccion' => 'Calle Puno 678, La Victoria', 'telefono' => '987654364', 'email' => 'fernando.rodriguez@mail.com', 'dni' => '44234567', 'fecha_nacimiento' => '1988-11-02', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Mónica Salazar', 'direccion' => 'Av. Pescadores 345, Chorrillos', 'telefono' => '987654365', 'email' => 'monica.salazar@mail.com', 'dni' => '45234567', 'fecha_nacimiento' => '1990-07-08', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Cristian Sánchez', 'direccion' => 'Jr. Lima 890, Villa El Salvador', 'telefono' => '987654366', 'email' => 'cristian.sanchez@mail.com', 'dni' => '46234567', 'fecha_nacimiento' => '1985-03-27', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Rosa González', 'direccion' => 'Calle Los Mangos 123, Comas', 'telefono' => '987654367', 'email' => 'rosa.gonzalez@mail.com', 'dni' => '47234567', 'fecha_nacimiento' => '1993-12-04', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Julio Alvarado', 'direccion' => 'Av. Los Andes 234, San Juan de Lurigancho', 'telefono' => '987654368', 'email' => 'julio.alvarado@mail.com', 'dni' => '48234567', 'fecha_nacimiento' => '1983-04-29', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Miriam Álvarez', 'direccion' => 'Jr. Talara 678, San Martín de Porres', 'telefono' => '987654369', 'email' => 'miriam.alvarez@mail.com', 'dni' => '49234567', 'fecha_nacimiento' => '1994-02-06', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Francisco Méndez', 'direccion' => 'Av. Santa Rosa 890, Ate', 'telefono' => '987654370', 'email' => 'francisco.mendez@mail.com', 'dni' => '50234567', 'fecha_nacimiento' => '1987-07-19', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Teresa Fernández', 'direccion' => 'Calle Los Molinos 123, Lince', 'telefono' => '987654371', 'email' => 'teresa.fernandez@mail.com', 'dni' => '51234567', 'fecha_nacimiento' => '1992-09-13', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'José Luis Castro', 'direccion' => 'Jr. Santa Cruz 234, Miraflores', 'telefono' => '987654372', 'email' => 'jose.castro@mail.com', 'dni' => '52234567', 'fecha_nacimiento' => '1990-11-21', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Sara Herrera', 'direccion' => 'Av. Progreso 345, Chorrillos', 'telefono' => '987654373', 'email' => 'sara.herrera@mail.com', 'dni' => '53234567', 'fecha_nacimiento' => '1995-06-09', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'premium'],
            ['nombre' => 'Ramón Rodríguez', 'direccion' => 'Calle El Sol 789, Barranco', 'telefono' => '987654374', 'email' => 'ramon.rodriguez@mail.com', 'dni' => '54234567', 'fecha_nacimiento' => '1986-04-17', 'genero' => 'masculino', 'activo' => true, 'tipo_cliente' => 'regular'],
            ['nombre' => 'Felisa Bravo', 'direccion' => 'Calle Los Pinos 234, San Isidro', 'telefono' => '987654375', 'email' => 'felisa.bravo@mail.com', 'dni' => '55234567', 'fecha_nacimiento' => '1991-05-23', 'genero' => 'femenino', 'activo' => true, 'tipo_cliente' => 'regular']
        ]);
    }
}
