<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{

    
    public function run(): void
    {
        DB::table('productos')->insert([
            ['nombre' => 'Teclado Mecánico RGB', 'precio' => 250.50, 'stock' => 30, 'id_categoria' => 18, 'id_proveedor' => 14, 'id_almacen' => 1],
            ['nombre' => 'Refrigeradora Inverter', 'precio' => 1900.00, 'stock' => 15, 'id_categoria' => 9, 'id_proveedor' => 1, 'id_almacen' => 2],
            ['nombre' => 'Parlante Bluetooth Portátil', 'precio' => 120.99, 'stock' => 50, 'id_categoria' => 5, 'id_proveedor' => 8, 'id_almacen' => 3],
            ['nombre' => 'Afeitadora Eléctrica', 'precio' => 85.00, 'stock' => 25, 'id_categoria' => 13, 'id_proveedor' => 9, 'id_almacen' => 1],
            ['nombre' => 'Drone Profesional 4K', 'precio' => 1500.75, 'stock' => 10, 'id_categoria' => 6, 'id_proveedor' => 3, 'id_almacen' => 2],
            ['nombre' => 'Tablet 10 pulgadas', 'precio' => 750.60, 'stock' => 20, 'id_categoria' => 27, 'id_proveedor' => 14, 'id_almacen' => 1],
            ['nombre' => 'Monitor 24 pulgadas', 'precio' => 450.00, 'stock' => 35, 'id_categoria' => 2, 'id_proveedor' => 11, 'id_almacen' => 3],
            ['nombre' => 'Deshumidificador Portátil', 'precio' => 400.20, 'stock' => 18, 'id_categoria' => 8, 'id_proveedor' => 10, 'id_almacen' => 2],
            ['nombre' => 'Tostadora Eléctrica', 'precio' => 65.00, 'stock' => 40, 'id_categoria' => 7, 'id_proveedor' => 5, 'id_almacen' => 3],
            ['nombre' => 'Bicicleta Estática', 'precio' => 950.50, 'stock' => 12, 'id_categoria' => 20, 'id_proveedor' => 13, 'id_almacen' => 1],
            ['nombre' => 'Impresora Multifuncional', 'precio' => 300.00, 'stock' => 22, 'id_categoria' => 27, 'id_proveedor' => 12, 'id_almacen' => 2],
            ['nombre' => 'Microondas 800W', 'precio' => 180.20, 'stock' => 28, 'id_categoria' => 7, 'id_proveedor' => 2, 'id_almacen' => 1],
            ['nombre' => 'Cámara de Seguridad WiFi', 'precio' => 250.00, 'stock' => 35, 'id_categoria' => 17, 'id_proveedor' => 6, 'id_almacen' => 3],
            ['nombre' => 'Batidora de Mano', 'precio' => 70.00, 'stock' => 45, 'id_categoria' => 7, 'id_proveedor' => 15, 'id_almacen' => 2],
            ['nombre' => 'Audífonos Inalámbricos', 'precio' => 120.00, 'stock' => 50, 'id_categoria' => 5, 'id_proveedor' => 8, 'id_almacen' => 1],
            ['nombre' => 'Aspiradora Robot', 'precio' => 500.00, 'stock' => 18, 'id_categoria' => 11, 'id_proveedor' => 7, 'id_almacen' => 3],
            ['nombre' => 'Cafetera de Cápsulas', 'precio' => 150.00, 'stock' => 30, 'id_categoria' => 7, 'id_proveedor' => 4, 'id_almacen' => 2],
            ['nombre' => 'Taladro Inalámbrico', 'precio' => 230.00, 'stock' => 25, 'id_categoria' => 22, 'id_proveedor' => 10, 'id_almacen' => 1],
            ['nombre' => 'Mesa de Centro Moderna', 'precio' => 350.00, 'stock' => 20, 'id_categoria' => 14, 'id_proveedor' => 16, 'id_almacen' => 2],
            ['nombre' => 'Ventilador de Torre', 'precio' => 110.00, 'stock' => 40, 'id_categoria' => 8, 'id_proveedor' => 5, 'id_almacen' => 3],
            ['nombre' => 'Smartwatch Deportivo', 'precio' => 300.00, 'stock' => 40, 'id_categoria' => 19, 'id_proveedor' => 8, 'id_almacen' => 1],
            ['nombre' => 'Cámara Réflex 24MP', 'precio' => 2500.00, 'stock' => 15, 'id_categoria' => 16, 'id_proveedor' => 14, 'id_almacen' => 2],
            ['nombre' => 'Aire Acondicionado Portátil', 'precio' => 1200.99, 'stock' => 10, 'id_categoria' => 8, 'id_proveedor' => 4, 'id_almacen' => 3],
            ['nombre' => 'Proyector HD', 'precio' => 850.75, 'stock' => 20, 'id_categoria' => 3, 'id_proveedor' => 11, 'id_almacen' => 1],
            ['nombre' => 'Cocina de Inducción', 'precio' => 670.30, 'stock' => 25, 'id_categoria' => 7, 'id_proveedor' => 2, 'id_almacen' => 2],
            ['nombre' => 'Plancha a Vapor', 'precio' => 90.50, 'stock' => 35, 'id_categoria' => 11, 'id_proveedor' => 12, 'id_almacen' => 3],
            ['nombre' => 'Smart TV 55 pulgadas', 'precio' => 3000.00, 'stock' => 12, 'id_categoria' => 4, 'id_proveedor' => 10, 'id_almacen' => 1],
            ['nombre' => 'Freidora de Aire', 'precio' => 250.00, 'stock' => 28, 'id_categoria' => 7, 'id_proveedor' => 15, 'id_almacen' => 2],
            ['nombre' => 'Reloj Inteligente Niños', 'precio' => 150.75, 'stock' => 30, 'id_categoria' => 19, 'id_proveedor' => 5, 'id_almacen' => 3],
            ['nombre' => 'Juego de Ollas Antiadherentes', 'precio' => 320.00, 'stock' => 40, 'id_categoria' => 12, 'id_proveedor' => 6, 'id_almacen' => 2],
            ['nombre' => 'Laptop Ultrabook', 'precio' => 4200.00, 'stock' => 18, 'id_categoria' => 1, 'id_proveedor' => 13, 'id_almacen' => 1],
            ['nombre' => 'Cámara de Video HD', 'precio' => 550.00, 'stock' => 22, 'id_categoria' => 16, 'id_proveedor' => 14, 'id_almacen' => 3],
            ['nombre' => 'Colchón Ortopédico', 'precio' => 700.00, 'stock' => 15, 'id_categoria' => 15, 'id_proveedor' => 1, 'id_almacen' => 2],
            ['nombre' => 'Mouse Gaming RGB', 'precio' => 80.99, 'stock' => 45, 'id_categoria' => 18, 'id_proveedor' => 8, 'id_almacen' => 1],
            ['nombre' => 'Escritorio Ajustable', 'precio' => 500.00, 'stock' => 20, 'id_categoria' => 14, 'id_proveedor' => 7, 'id_almacen' => 3],
            ['nombre' => 'Kit de Destornilladores', 'precio' => 40.00, 'stock' => 50, 'id_categoria' => 22, 'id_proveedor' => 3, 'id_almacen' => 1],
            ['nombre' => 'Máquina de Coser Portátil', 'precio' => 350.00, 'stock' => 18, 'id_categoria' => 11, 'id_proveedor' => 5, 'id_almacen' => 2],
            ['nombre' => 'Auriculares Over-Ear', 'precio' => 250.00, 'stock' => 38, 'id_categoria' => 5, 'id_proveedor' => 9, 'id_almacen' => 3],
            ['nombre' => 'Calentador de Agua Eléctrico', 'precio' => 180.00, 'stock' => 32, 'id_categoria' => 11, 'id_proveedor' => 16, 'id_almacen' => 1],
            ['nombre' => 'Ventilador de Pared', 'precio' => 120.50, 'stock' => 40, 'id_categoria' => 8, 'id_proveedor' => 4, 'id_almacen' => 2],
            ['nombre' => 'Cafetería Expresso', 'precio' => 80.00, 'stock' => 25, 'id_categoria' => 10, 'id_proveedor' => 17, 'id_almacen' => 3],
            ['nombre' => 'Cafetería Cappuccino', 'precio' => 90.00, 'stock' => 30, 'id_categoria' => 10, 'id_proveedor' => 17, 'id_almacen' => 1],
            ['nombre' => 'Licuadora Portátil', 'precio' => 120.30, 'stock' => 32, 'id_categoria' => 7, 'id_proveedor' => 3, 'id_almacen' => 2],
            ['nombre' => 'Calefactor Cerámico', 'precio' => 250.75, 'stock' => 28, 'id_categoria' => 8, 'id_proveedor' => 12, 'id_almacen' => 1],
            ['nombre' => 'Cámara Instantánea', 'precio' => 300.99, 'stock' => 25, 'id_categoria' => 16, 'id_proveedor' => 14, 'id_almacen' => 3],
            ['nombre' => 'Humidificador Ultrasónico', 'precio' => 70.20, 'stock' => 40, 'id_categoria' => 8, 'id_proveedor' => 9, 'id_almacen' => 2],
            ['nombre' => 'Audífonos de Diadema', 'precio' => 130.50, 'stock' => 30, 'id_categoria' => 5, 'id_proveedor' => 4, 'id_almacen' => 1],
            ['nombre' => 'Cargador Solar Portátil', 'precio' => 50.00, 'stock' => 45, 'id_categoria' => 3, 'id_proveedor' => 10, 'id_almacen' => 3],
            ['nombre' => 'Tijeras Eléctricas', 'precio' => 95.99, 'stock' => 20, 'id_categoria' => 22, 'id_proveedor' => 8, 'id_almacen' => 1],
            ['nombre' => 'Smartphone 5G', 'precio' => 2700.00, 'stock' => 18, 'id_categoria' => 1, 'id_proveedor' => 7, 'id_almacen' => 2],
            ['nombre' => 'Impresora 3D', 'precio' => 1200.50, 'stock' => 10, 'id_categoria' => 27, 'id_proveedor' => 15, 'id_almacen' => 3],
            ['nombre' => 'Lámpara LED Recargable', 'precio' => 45.20, 'stock' => 50, 'id_categoria' => 13, 'id_proveedor' => 6, 'id_almacen' => 1],
            ['nombre' => 'Smart Lock WiFi', 'precio' => 350.00, 'stock' => 25, 'id_categoria' => 17, 'id_proveedor' => 5, 'id_almacen' => 2],
            ['nombre' => 'Auriculares con Cancelación de Ruido', 'precio' => 270.00, 'stock' => 30, 'id_categoria' => 5, 'id_proveedor' => 11, 'id_almacen' => 1],
            ['nombre' => 'Router WiFi 6', 'precio' => 300.00, 'stock' => 35, 'id_categoria' => 3, 'id_proveedor' => 4, 'id_almacen' => 2],
            ['nombre' => 'Sierra Eléctrica', 'precio' => 450.00, 'stock' => 20, 'id_categoria' => 22, 'id_proveedor' => 2, 'id_almacen' => 3],
            ['nombre' => 'Cámara de Vigilancia Solar', 'precio' => 600.00, 'stock' => 15, 'id_categoria' => 17, 'id_proveedor' => 14, 'id_almacen' => 1],
            ['nombre' => 'Patineta Eléctrica', 'precio' => 1800.00, 'stock' => 10, 'id_categoria' => 20, 'id_proveedor' => 13, 'id_almacen' => 3],
            ['nombre' => 'Calentador de Terma Solar', 'precio' => 850.00, 'stock' => 8, 'id_categoria' => 11, 'id_proveedor' => 1, 'id_almacen' => 2],
            ['nombre' => 'Teclado Ergonómico Inalámbrico', 'precio' => 140.99, 'stock' => 45, 'id_categoria' => 18, 'id_proveedor' => 3, 'id_almacen' => 1],
            ['nombre' => 'Cámara de Acción 4K', 'precio' => 950.00, 'stock' => 22, 'id_categoria' => 16, 'id_proveedor' => 10, 'id_almacen' => 2],
            ['nombre' => 'Despertador Inteligente', 'precio' => 60.00, 'stock' => 50, 'id_categoria' => 10, 'id_proveedor' => 7, 'id_almacen' => 3],
            ['nombre' => 'Purificador de Aire', 'precio' => 300.00, 'stock' => 20, 'id_categoria' => 8, 'id_proveedor' => 11, 'id_almacen' => 1],
            ['nombre' => 'Cámara de Seguridad IP', 'precio' => 150.00, 'stock' => 30, 'id_categoria' => 17, 'id_proveedor' => 12, 'id_almacen' => 2],
            ['nombre' => 'Batería Externa 20000mAh', 'precio' => 50.00, 'stock' => 40, 'id_categoria' => 3, 'id_proveedor' => 13, 'id_almacen' => 3],
            ['nombre' => 'Lámpara de Escritorio LED', 'precio' => 25.00, 'stock' => 50, 'id_categoria' => 13, 'id_proveedor' => 14, 'id_almacen' => 1],
            ['nombre' => 'Cámara Deportiva 1080p', 'precio' => 120.00, 'stock' => 35, 'id_categoria' => 16, 'id_proveedor' => 15, 'id_almacen' => 2],
            ['nombre' => 'Smartwatch con GPS', 'precio' => 200.00, 'stock' => 25, 'id_categoria' => 19, 'id_proveedor' => 16, 'id_almacen' => 3],
            ['nombre' => 'Proyector Portátil', 'precio' => 400.00, 'stock' => 15, 'id_categoria' => 3, 'id_proveedor' => 17, 'id_almacen' => 1],
            ['nombre' => 'Cafetera Automática', 'precio' => 300.00, 'stock' => 20, 'id_categoria' => 7, 'id_proveedor' => 18, 'id_almacen' => 2],
            ['nombre' => 'Aspiradora Sin Bolsa', 'precio' => 150.00, 'stock' => 30, 'id_categoria' => 11, 'id_proveedor' => 19, 'id_almacen' => 3],
            ['nombre' => 'Cámara de Video 4K', 'precio' => 800.00, 'stock' => 10, 'id_categoria' => 16, 'id_proveedor' => 20, 'id_almacen' => 1],
            ['nombre' => 'Monitor Curvo 27 pulgadas', 'precio' => 600.00, 'stock' => 12, 'id_categoria' => 2, 'id_proveedor' => 21, 'id_almacen' => 2],
            ['nombre' => 'Impresora Láser', 'precio' => 350.00, 'stock' => 18, 'id_categoria' => 27, 'id_proveedor' => 22, 'id_almacen' => 3],
            ['nombre' => 'Router Mesh WiFi', 'precio' => 250.00, 'stock' => 25, 'id_categoria' => 3, 'id_proveedor' => 23, 'id_almacen' => 1],
            ['nombre' => 'Cámara de Seguridad Exterior', 'precio' => 200.00, 'stock' => 20, 'id_categoria' => 17, 'id_proveedor' => 24, 'id_almacen' => 2],
            ['nombre' => 'Smartwatch con Monitor de Ritmo Cardíaco', 'precio' => 150.00, 'stock' => 30, 'id_categoria' => 19, 'id_proveedor' => 25, 'id_almacen' => 3],
            ['nombre' => 'Proyector 4K', 'precio' => 2000.00, 'stock' => 10, 'id_categoria' => 3, 'id_proveedor' => 6, 'id_almacen' => 1],
            ['nombre' => 'Cámara de Seguridad 4K', 'precio' => 350.00, 'stock' => 15, 'id_categoria' => 17, 'id_proveedor' => 7, 'id_almacen' => 2],
            ['nombre' => 'Laptop Gaming', 'precio' => 4500.00, 'stock' => 8, 'id_categoria' => 1, 'id_proveedor' => 8, 'id_almacen' => 3],
            ['nombre' => 'Reloj Inteligente', 'precio' => 150.00, 'stock' => 30, 'id_categoria' => 19, 'id_proveedor' => 5, 'id_almacen' => 1],
            ['nombre' => 'Altavoz Inalámbrico', 'precio' => 120.00, 'stock' => 40, 'id_categoria' => 5, 'id_proveedor' => 9, 'id_almacen' => 2],
            ['nombre' => 'Monitor Curvo 32"', 'precio' => 950.50, 'stock' => 25, 'id_categoria' => 2, 'id_proveedor' => 4, 'id_almacen' => 1],
            ['nombre' => 'Mochila Gaming', 'precio' => 85.00, 'stock' => 50, 'id_categoria' => 18, 'id_proveedor' => 15, 'id_almacen' => 3],
            ['nombre' => 'Teclado Mecánico RGB', 'precio' => 180.00, 'stock' => 22, 'id_categoria' => 18, 'id_proveedor' => 6, 'id_almacen' => 2],
            ['nombre' => 'Cámara de Seguridad PTZ', 'precio' => 550.00, 'stock' => 18, 'id_categoria' => 17, 'id_proveedor' => 8, 'id_almacen' => 1],
            ['nombre' => 'Tablet 12 pulgadas', 'precio' => 850.50, 'stock' => 20, 'id_categoria' => 27, 'id_proveedor' => 14, 'id_almacen' => 3],
            ['nombre' => 'Freidora de Aire 5L', 'precio' => 180.00, 'stock' => 30, 'id_categoria' => 7, 'id_proveedor' => 12, 'id_almacen' => 2],
            ['nombre' => 'Cámara de Video Profesional', 'precio' => 4500.00, 'stock' => 10, 'id_categoria' => 16, 'id_proveedor' => 13, 'id_almacen' => 1],
            ['nombre' => 'Bicicleta de Montaña', 'precio' => 800.00, 'stock' => 15, 'id_categoria' => 20, 'id_proveedor' => 3, 'id_almacen' => 2],
            ['nombre' => 'Mini Heladera', 'precio' => 95.00, 'stock' => 40, 'id_categoria' => 9, 'id_proveedor' => 14, 'id_almacen' => 3],
            ['nombre' => 'Licuadora de Alta Potencia', 'precio' => 110.00, 'stock' => 35, 'id_categoria' => 7, 'id_proveedor' => 4, 'id_almacen' => 1],
            ['nombre' => 'Reproductor Blu-Ray', 'precio' => 220.00, 'stock' => 18, 'id_categoria' => 4, 'id_proveedor' => 5, 'id_almacen' => 2],
            ['nombre' => 'Cámara Digital', 'precio' => 1200.00, 'stock' => 20, 'id_categoria' => 16, 'id_proveedor' => 7, 'id_almacen' => 1],
            ['nombre' => 'Horno Eléctrico', 'precio' => 450.00, 'stock' => 22, 'id_categoria' => 7, 'id_proveedor' => 16, 'id_almacen' => 3],
            ['nombre' => 'Smartphone 6.5"', 'precio' => 950.00, 'stock' => 30, 'id_categoria' => 1, 'id_proveedor' => 10, 'id_almacen' => 2],
            ['nombre' => 'Auriculares Bluetooth', 'precio' => 90.00, 'stock' => 50, 'id_categoria' => 5, 'id_proveedor' => 9, 'id_almacen' => 1],
            ['nombre' => 'Teclado Gaming RGB', 'precio' => 200.00, 'stock' => 15, 'id_categoria' => 18, 'id_proveedor' => 4, 'id_almacen' => 2],
            ['nombre' => 'Impresora Multifuncional', 'precio' => 150.00, 'stock' => 20, 'id_categoria' => 6, 'id_proveedor' => 7, 'id_almacen' => 3],
            ['nombre' => 'Smartwatch con GPS', 'precio' => 250.00, 'stock' => 18, 'id_categoria' => 19, 'id_proveedor' => 8, 'id_almacen' => 1],
            ['nombre' => 'Barra de Sonido', 'precio' => 350.00, 'stock' => 25, 'id_categoria' => 5, 'id_proveedor' => 10, 'id_almacen' => 2],
            ['nombre' => 'Portátil 15.6"', 'precio' => 950.00, 'stock' => 10, 'id_categoria' => 1, 'id_proveedor' => 11, 'id_almacen' => 3],
            ['nombre' => 'Cámara Instantánea', 'precio' => 120.00, 'stock' => 30, 'id_categoria' => 16, 'id_proveedor' => 12, 'id_almacen' => 1],
            ['nombre' => 'Silla Ergonómica', 'precio' => 180.00, 'stock' => 12, 'id_categoria' => 18, 'id_proveedor' => 13, 'id_almacen' => 2],
            ['nombre' => 'Lente de Contacto 30 días', 'precio' => 25.00, 'stock' => 60, 'id_categoria' => 15, 'id_proveedor' => 6, 'id_almacen' => 3],
            ['nombre' => 'Pantalla LED 24"', 'precio' => 220.00, 'stock' => 35, 'id_categoria' => 2, 'id_proveedor' => 9, 'id_almacen' => 1],
            ['nombre' => 'Mini Proyector', 'precio' => 150.00, 'stock' => 40, 'id_categoria' => 3, 'id_proveedor' => 14, 'id_almacen' => 2],
            ['nombre' => 'Móvil 6.2"', 'precio' => 800.00, 'stock' => 25, 'id_categoria' => 1, 'id_proveedor' => 15, 'id_almacen' => 3],
            ['nombre' => 'Gafas VR', 'precio' => 300.00, 'stock' => 10, 'id_categoria' => 20, 'id_proveedor' => 16, 'id_almacen' => 1],
            ['nombre' => 'Sistema de Sonido Home Theater', 'precio' => 500.00, 'stock' => 15, 'id_categoria' => 5, 'id_proveedor' => 17, 'id_almacen' => 2],
            ['nombre' => 'Cafetera Automática', 'precio' => 350.00, 'stock' => 30, 'id_categoria' => 7, 'id_proveedor' => 4, 'id_almacen' => 3],
            ['nombre' => 'Mochila Escolar', 'precio' => 40.00, 'stock' => 50, 'id_categoria' => 18, 'id_proveedor' => 18, 'id_almacen' => 1],
            ['nombre' => 'Luces LED RGB', 'precio' => 60.00, 'stock' => 40, 'id_categoria' => 8, 'id_proveedor' => 19, 'id_almacen' => 2],
            ['nombre' => 'Microondas Digital', 'precio' => 120.00, 'stock' => 18, 'id_categoria' => 9, 'id_proveedor' => 5, 'id_almacen' => 3],
            ['nombre' => 'Bicicross', 'precio' => 350.00, 'stock' => 12, 'id_categoria' => 20, 'id_proveedor' => 20, 'id_almacen' => 1],
            ['nombre' => 'Monitor 27" 4K', 'precio' => 400.00, 'stock' => 30, 'id_categoria' => 2, 'id_proveedor' => 4, 'id_almacen' => 1],
            ['nombre' => 'Teclado Mecánico', 'precio' => 120.00, 'stock' => 50, 'id_categoria' => 18, 'id_proveedor' => 5, 'id_almacen' => 2],
            ['nombre' => 'Móvil 6.5"', 'precio' => 650.00, 'stock' => 20, 'id_categoria' => 1, 'id_proveedor' => 6, 'id_almacen' => 3],
            ['nombre' => 'Lámpara LED Inteligente', 'precio' => 35.00, 'stock' => 70, 'id_categoria' => 8, 'id_proveedor' => 7, 'id_almacen' => 1],
            ['nombre' => 'Smart TV 55"', 'precio' => 700.00, 'stock' => 15, 'id_categoria' => 5, 'id_proveedor' => 8, 'id_almacen' => 2],
            ['nombre' => 'Bicicleta Eléctrica', 'precio' => 900.00, 'stock' => 8, 'id_categoria' => 20, 'id_proveedor' => 9, 'id_almacen' => 3],
            ['nombre' => 'Cámara Profesional', 'precio' => 850.00, 'stock' => 12, 'id_categoria' => 16, 'id_proveedor' => 10, 'id_almacen' => 1],
            ['nombre' => 'Gimnasio en Casa', 'precio' => 200.00, 'stock' => 20, 'id_categoria' => 19, 'id_proveedor' => 11, 'id_almacen' => 2],
            ['nombre' => 'Robot Aspiradora', 'precio' => 250.00, 'stock' => 18, 'id_categoria' => 7, 'id_proveedor' => 12, 'id_almacen' => 3],
            ['nombre' => 'Altavoces Bluetooth', 'precio' => 80.00, 'stock' => 35, 'id_categoria' => 5, 'id_proveedor' => 13, 'id_almacen' => 1],
            ['nombre' => 'Cargador Solar Portátil', 'precio' => 40.00, 'stock' => 50, 'id_categoria' => 6, 'id_proveedor' => 14, 'id_almacen' => 2],
            ['nombre' => 'Estación Meteorológica', 'precio' => 100.00, 'stock' => 28, 'id_categoria' => 5, 'id_proveedor' => 15, 'id_almacen' => 3],
            ['nombre' => 'Smartphone 5G', 'precio' => 750.00, 'stock' => 25, 'id_categoria' => 1, 'id_proveedor' => 16, 'id_almacen' => 1],
            ['nombre' => 'Auriculares Inalámbricos', 'precio' => 130.00, 'stock' => 40, 'id_categoria' => 18, 'id_proveedor' => 17, 'id_almacen' => 2],
            ['nombre' => 'Silla de Oficina', 'precio' => 90.00, 'stock' => 60, 'id_categoria' => 18, 'id_proveedor' => 18, 'id_almacen' => 3],
            ['nombre' => 'Cámara de Seguridad', 'precio' => 200.00, 'stock' => 15, 'id_categoria' => 16, 'id_proveedor' => 19, 'id_almacen' => 1],
            ['nombre' => 'Micrófono Profesional', 'precio' => 110.00, 'stock' => 30, 'id_categoria' => 16, 'id_proveedor' => 20, 'id_almacen' => 2],
            ['nombre' => 'Bocina Portátil', 'precio' => 55.00, 'stock' => 50, 'id_categoria' => 5, 'id_proveedor' => 4, 'id_almacen' => 3],
            ['nombre' => 'Impresora 3D', 'precio' => 600.00, 'stock' => 10, 'id_categoria' => 6, 'id_proveedor' => 5, 'id_almacen' => 1],
            ['nombre' => 'Paseo Eléctrico', 'precio' => 300.00, 'stock' => 15, 'id_categoria' => 20, 'id_proveedor' => 6, 'id_almacen' => 2],
            ['nombre' => 'Cámara de Acción 4K', 'precio' => 250.00, 'stock' => 40, 'id_categoria' => 16, 'id_proveedor' => 7, 'id_almacen' => 1],
            ['nombre' => 'Teclado Inalámbrico', 'precio' => 60.00, 'stock' => 50, 'id_categoria' => 18, 'id_proveedor' => 8, 'id_almacen' => 2],
            ['nombre' => 'Smartwatch Deportivo', 'precio' => 150.00, 'stock' => 60, 'id_categoria' => 3, 'id_proveedor' => 9, 'id_almacen' => 3],
            ['nombre' => 'Consola de Videojuegos', 'precio' => 400.00, 'stock' => 25, 'id_categoria' => 4, 'id_proveedor' => 10, 'id_almacen' => 1],
            ['nombre' => 'Monitor Curvo 32"', 'precio' => 350.00, 'stock' => 35, 'id_categoria' => 2, 'id_proveedor' => 11, 'id_almacen' => 2],
            ['nombre' => 'Disco Duro Externo 1TB', 'precio' => 80.00, 'stock' => 100, 'id_categoria' => 7, 'id_proveedor' => 12, 'id_almacen' => 3],
            ['nombre' => 'Router Wi-Fi 6', 'precio' => 120.00, 'stock' => 60, 'id_categoria' => 8, 'id_proveedor' => 13, 'id_almacen' => 1],
            ['nombre' => 'Estuche para Laptop', 'precio' => 30.00, 'stock' => 80, 'id_categoria' => 18, 'id_proveedor' => 14, 'id_almacen' => 2],
            ['nombre' => 'Proyector LED Portátil', 'precio' => 220.00, 'stock' => 20, 'id_categoria' => 17, 'id_proveedor' => 15, 'id_almacen' => 3],
            ['nombre' => 'Silla Gamer', 'precio' => 150.00, 'stock' => 30, 'id_categoria' => 19, 'id_proveedor' => 16, 'id_almacen' => 1],
            ['nombre' => 'Lentes VR', 'precio' => 200.00, 'stock' => 50, 'id_categoria' => 4, 'id_proveedor' => 17, 'id_almacen' => 2],
            ['nombre' => 'Cargador Inalámbrico', 'precio' => 25.00, 'stock' => 70, 'id_categoria' => 6, 'id_proveedor' => 18, 'id_almacen' => 3],
            ['nombre' => 'Parlantes Estéreo', 'precio' => 90.00, 'stock' => 60, 'id_categoria' => 5, 'id_proveedor' => 19, 'id_almacen' => 1],
            ['nombre' => 'Cámara de Seguridad IP', 'precio' => 180.00, 'stock' => 30, 'id_categoria' => 16, 'id_proveedor' => 20, 'id_almacen' => 2],
            ['nombre' => 'Torre de Sonido', 'precio' => 130.00, 'stock' => 25, 'id_categoria' => 5, 'id_proveedor' => 7, 'id_almacen' => 3],
            ['nombre' => 'Sofá Inteligente', 'precio' => 400.00, 'stock' => 15, 'id_categoria' => 19, 'id_proveedor' => 8, 'id_almacen' => 1],
            ['nombre' => 'Cargador Solar para Móvil', 'precio' => 50.00, 'stock' => 45, 'id_categoria' => 6, 'id_proveedor' => 9, 'id_almacen' => 2],
            ['nombre' => 'Ventilador Eléctrico Inteligente', 'precio' => 100.00, 'stock' => 50, 'id_categoria' => 19, 'id_proveedor' => 10, 'id_almacen' => 3],
            ['nombre' => 'Termo Inteligente', 'precio' => 35.00, 'stock' => 70, 'id_categoria' => 8, 'id_proveedor' => 11, 'id_almacen' => 1],
            ['nombre' => 'Robot de Cocina', 'precio' => 250.00, 'stock' => 20, 'id_categoria' => 20, 'id_proveedor' => 12, 'id_almacen' => 2],
            ['nombre' => 'Cámara Digital Reflex', 'precio' => 500.00, 'stock' => 15, 'id_categoria' => 16, 'id_proveedor' => 13, 'id_almacen' => 1],
            ['nombre' => 'Audífonos Bluetooth', 'precio' => 60.00, 'stock' => 80, 'id_categoria' => 5, 'id_proveedor' => 14, 'id_almacen' => 2],
            ['nombre' => 'Microondas Inverter', 'precio' => 220.00, 'stock' => 40, 'id_categoria' => 20, 'id_proveedor' => 15, 'id_almacen' => 3],
            ['nombre' => 'Bocinas Bluetooth Portátiles', 'precio' => 70.00, 'stock' => 90, 'id_categoria' => 5, 'id_proveedor' => 16, 'id_almacen' => 1],
            ['nombre' => 'Bicicleta Eléctrica', 'precio' => 850.00, 'stock' => 10, 'id_categoria' => 3, 'id_proveedor' => 17, 'id_almacen' => 2],
            ['nombre' => 'Horno Eléctrico', 'precio' => 180.00, 'stock' => 30, 'id_categoria' => 20, 'id_proveedor' => 18, 'id_almacen' => 3],
            ['nombre' => 'Escáner Portátil', 'precio' => 120.00, 'stock' => 50, 'id_categoria' => 2, 'id_proveedor' => 19, 'id_almacen' => 1],
            ['nombre' => 'Proyector de Cine en Casa', 'precio' => 450.00, 'stock' => 20, 'id_categoria' => 17, 'id_proveedor' => 20, 'id_almacen' => 2],
            ['nombre' => 'Silla Ergonómica', 'precio' => 180.00, 'stock' => 70, 'id_categoria' => 19, 'id_proveedor' => 13, 'id_almacen' => 3],
            ['nombre' => 'Smartphone 5G', 'precio' => 600.00, 'stock' => 25, 'id_categoria' => 4, 'id_proveedor' => 14, 'id_almacen' => 1],
            ['nombre' => 'Cargador Inalámbrico para Móvil', 'precio' => 30.00, 'stock' => 100, 'id_categoria' => 6, 'id_proveedor' => 15, 'id_almacen' => 2],
            ['nombre' => 'Teclado Mecánico RGB', 'precio' => 100.00, 'stock' => 55, 'id_categoria' => 18, 'id_proveedor' => 16, 'id_almacen' => 3],
            ['nombre' => 'Mochila para Laptop', 'precio' => 50.00, 'stock' => 60, 'id_categoria' => 18, 'id_proveedor' => 17, 'id_almacen' => 1],
            ['nombre' => 'Pantalla 4K Ultra HD', 'precio' => 350.00, 'stock' => 15, 'id_categoria' => 2, 'id_proveedor' => 18, 'id_almacen' => 2],
            ['nombre' => 'Cafetera Eléctrica', 'precio' => 80.00, 'stock' => 70, 'id_categoria' => 20, 'id_proveedor' => 19, 'id_almacen' => 3],
            ['nombre' => 'Lámpara de Escritorio LED', 'precio' => 40.00, 'stock' => 120, 'id_categoria' => 19, 'id_proveedor' => 20, 'id_almacen' => 1],
            ['nombre' => 'Smart TV 55"', 'precio' => 750.00, 'stock' => 10, 'id_categoria' => 17, 'id_proveedor' => 13, 'id_almacen' => 2],
            ['nombre' => 'Cámara IP de Seguridad', 'precio' => 130.00, 'stock' => 45, 'id_categoria' => 16, 'id_proveedor' => 14, 'id_almacen' => 3],
            ['nombre' => 'Estabilizador de Voltaje', 'precio' => 70.00, 'stock' => 60, 'id_categoria' => 5, 'id_proveedor' => 15, 'id_almacen' => 1],
        ]);

    }
}
